// AUTHENTICATION
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// PROFILE
export const FETCH_PROFILE_START = 'FETCH_PROFILE_START';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';

export const ADD_PROFILE_START = 'ADD_PROFILE_START';
export const ADD_PROFILE_SUCCESS = 'ADD_PROFILE_SUCCESS';
export const ADD_PROFILE_FAILURE = 'ADD_PROFILE_FAILURE';

export const EDIT_PROFILE_START = 'EDIT_PROFILE_START';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';

// GAMES
export const FETCH_GAMES_START = 'FETCH_GAMES_START';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAILURE = 'FETCH_GAMES_FAILURE';

export const FETCH_GAME_START = 'FETCH_GAME_START';
export const FETCH_GAME_SUCCESS = 'FETCH_GAME_SUCCESS';
export const FETCH_GAME_FAILURE = 'FETCH_GAME_FAILURE';

export const ADD_GAME_START = 'ADD_GAME_START';
export const ADD_GAME_SUCCESS = 'ADD_GAME_SUCCESS';
export const ADD_GAME_FAILURE = 'ADD_GAME_FAILURE';

export const EDIT_GAME_START = 'EDIT_GAME_START';
export const EDIT_GAME_SUCCESS = 'EDIT_GAME_SUCCESS';
export const EDIT_GAME_FAILURE = 'EDIT_GAME_FAILURE';

export const DELETE_GAME_START = 'DELETE_GAME_START';
export const DELETE_GAME_SUCCESS = 'DELETE_GAME_SUCCESS';
export const DELETE_GAME_FAILURE = 'DELETE_GAME_FAILURE';

// ROUNDS
export const FETCH_ROUNDS_START = 'FETCH_ROUNDS_START';
export const FETCH_ROUNDS_SUCCESS = 'FETCH_ROUNDS_SUCCESS';
export const FETCH_ROUNDS_FAILURE = 'FETCH_ROUNDS_FAILURE';

export const FETCH_ROUND_START = 'FETCH_ROUND_START';
export const FETCH_ROUND_SUCCESS = 'FETCH_ROUND_SUCCESS';
export const FETCH_ROUND_FAILURE = 'FETCH_ROUND_FAILURE';

export const ADD_ROUND_START = 'ADD_ROUND_START';
export const ADD_ROUND_SUCCESS = 'ADD_ROUND_SUCCESS';
export const ADD_ROUND_FAILURE = 'ADD_ROUND_FAILURE';

export const EDIT_ROUND_START = 'EDIT_ROUND_START';
export const EDIT_ROUND_SUCCESS = 'EDIT_ROUND_SUCCESS';
export const EDIT_ROUND_FAILURE = 'EDIT_ROUND_FAILURE';

export const DELETE_ROUND_START = 'DELETE_ROUND_START';
export const DELETE_ROUND_SUCCESS = 'DELETE_ROUND_SUCCESS';
export const DELETE_ROUND_FAILURE = 'DELETE_ROUND_FAILURE';

// QUESTIONS
export const FETCH_QUESTIONS_START = 'FETCH_QUESTIONS_START';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_FAILURE = 'FETCH_QUESTIONS_FAILURE';

export const FETCH_OPENTDB_QUESTIONS_START = 'FETCH_OPENTDB_QUESTIONS_START';
export const FETCH_OPENTDB_QUESTIONS_SUCCESS = 'FETCH_OPENTDB_QUESTIONS_SUCCESS';
export const FETCH_OPENTDB_QUESTIONS_FAILURE = 'FETCH_OPENTDB_QUESTIONS_FAILURE';

export const FETCH_QUESTION_START = 'FETCH_QUESTION_START';
export const FETCH_QUESTION_SUCCESS = 'FETCH_QUESTION_SUCCESS';
export const FETCH_QUESTION_FAILURE = 'FETCH_QUESTION_FAILURE';

export const ADD_QUESTION_START = 'ADD_QUESTION_START';
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';
export const ADD_QUESTION_FAILURE = 'ADD_QUESTION_FAILURE';

export const EDIT_QUESTION_START = 'EDIT_QUESTION_START';
export const EDIT_QUESTION_SUCCESS = 'EDIT_QUESTION_SUCCESS';
export const EDIT_QUESTION_FAILURE = 'EDIT_QUESTION_FAILURE';

export const DELETE_QUESTION_START = 'DELETE_QUESTION_START';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';
export const DELETE_QUESTION_FAILURE = 'DELETE_QUESTION_FAILURE';

// ANSWERS
export const FETCH_ANSWERS_START = 'FETCH_ANSWERS_START';
export const FETCH_ANSWERS_SUCCESS = 'FETCH_ANSWERS_SUCCESS';
export const FETCH_ANSWERS_FAILURE = 'FETCH_ANSWERS_FAILURE';

export const FETCH_ANSWER_START = 'FETCH_ANSWER_START';
export const FETCH_ANSWER_SUCCESS = 'FETCH_ANSWER_SUCCESS';
export const FETCH_ANSWER_FAILURE = 'FETCH_ANSWER_FAILURE';

export const ADD_ANSWER_START = 'ADD_ANSWER_START';
export const ADD_ANSWER_SUCCESS = 'ADD_ANSWER_SUCCESS';
export const ADD_ANSWER_FAILURE = 'ADD_ANSWER_FAILURE';

export const EDIT_ANSWER_START = 'EDIT_ANSWER_START';
export const EDIT_ANSWER_SUCCESS = 'EDIT_ANSWER_SUCCESS';
export const EDIT_ANSWER_FAILURE = 'EDIT_ANSWER_FAILURE';

export const DELETE_ANSWER_START = 'DELETE_ANSWER_START';
export const DELETE_ANSWER_SUCCESS = 'DELETE_ANSWER_SUCCESS';
export const DELETE_ANSWER_FAILURE = 'DELETE_ANSWER_FAILURE';

// CATEGORIES
export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

