// AUTHENTICATION
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

// ANSWERS
export const FETCH_ANSWERS_START = 'FETCH_ANSWERS_START';
export const FETCH_ANSWERS_SUCCESS = 'FETCH_ANSWERS_SUCCESS';
export const FETCH_ANSWERS_FAILURE = 'FETCH_ANSWERS_FAILURE';

export const ADD_ANSWER_START = 'ADD_ANSWER_START';
export const ADD_ANSWER_SUCCESS = 'ADD_ANSWER_SUCCESS';
export const ADD_ANSWER_FAILURE = 'ADD_ANSWER_FAILURE';

export const EDIT_ANSWER_START = 'EDIT_ANSWER_START';
export const EDIT_ANSWER_SUCCESS = 'EDIT_ANSWER_SUCCESS';
export const EDIT_ANSWER_FAILURE = 'EDIT_ANSWER_FAILURE';

export const DELETE_ANSWER_START = 'DELETE_ANSWER_START';
export const DELETE_ANSWER_SUCCESS = 'DELETE_ANSWER_SUCCESS';
export const DELETE_ANSWER_FAILURE = 'DELETE_ANSWER_FAILURE';

// GAMES
export const FETCH_GAMES_START = 'FETCH_GAMES_START';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAILURE = 'FETCH_GAMES_FAILURE';

export const FETCH_GAME_START = 'FETCH_GAME_START';
export const FETCH_GAME_SUCCESS = 'FETCH_GAME_SUCCESS';
export const FETCH_GAME_FAILURE = 'FETCH_GAME_FAILURE';

export const ADD_GAME_START = 'ADD_GAME_START';
export const ADD_GAME_SUCCESS = 'ADD_GAME_SUCCESS';
export const ADD_GAME_FAILURE = 'ADD_GAME_FAILURE';

export const EDIT_GAME_START = 'EDIT_GAME_START';
export const EDIT_GAME_SUCCESS = 'EDIT_GAME_SUCCESS';
export const EDIT_GAME_FAILURE = 'EDIT_GAME_FAILURE';

export const DELETE_GAME_START = 'DELETE_GAME_START';
export const DELETE_GAME_SUCCESS = 'DELETE_GAME_SUCCESS';
export const DELETE_GAME_FAILURE = 'DELETE_GAME_FAILURE';
